name: Deploy Stack

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      RIGHTMOVE_URL: ${{ secrets.RIGHTMOVE_URL }}
      ALERT_EMAIL: ${{ secrets.ALERT_EMAIL }}
      AWS_DEFAULT_REGION: eu-west-2

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Set up local env
        run: |
          pip install pipenv
          pip install aws-sam-cli

      - name: Deploy Lambda Function
        run: deploy/deploy.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ env.AWS_DEFAULT_REGION }}
          RIGHTMOVE_URL: ${{ env.RIGHTMOVE_URL }}
          ALERT_EMAIL: ${{ env.ALERT_EMAIL }}
